"""
Step 6 -- Person B: run the feedback-scoring prompt for real.

Prefers real transcripts generated by generate_test_transcripts.py
(from the ML Round conversation engine). Falls back to the hand-written
sample_transcripts.py stand-ins if no real transcripts exist yet.

To generate real transcripts:
    python -m interview_engine.generate_test_transcripts
"""

import json
import os
import time

from groq import BadRequestError, RateLimitError
from pydantic import ValidationError

from interview_engine.feedback_prompt import call_groq
from interview_engine.feedback_schema import FeedbackScore


TRANSCRIPTS_DIR = os.path.join(os.path.dirname(__file__), "test_transcripts")


def _load_real_transcripts() -> dict[str, str]:
    """Load transcripts from test_transcripts/ if the directory exists."""
    index_path = os.path.join(TRANSCRIPTS_DIR, "index.json")
    if not os.path.exists(index_path):
        return {}

    with open(index_path, encoding="utf-8") as f:
        index = json.load(f)

    transcripts = {}
    for entry in index:
        txt_path = os.path.join(TRANSCRIPTS_DIR, entry["file"])
        if os.path.exists(txt_path):
            with open(txt_path, encoding="utf-8") as f:
                transcripts[entry["name"]] = f.read()

    return transcripts


def _load_sample_transcripts() -> dict[str, str]:
    """Fall back to the hand-written stand-ins."""
    from interview_engine.sample_transcripts import ALL_SAMPLES
    return ALL_SAMPLES


def get_transcripts() -> dict[str, str]:
    """Return real transcripts if available, otherwise the hand-written samples."""
    real = _load_real_transcripts()
    if real:
        print(f"Using {len(real)} real transcripts from test_transcripts/\n")
        return real
    print("No real transcripts found -- using hand-written samples as fallback\n")
    return _load_sample_transcripts()


def call_groq_with_retry(transcript: str, max_retries: int = 4) -> str | None:
    for attempt in range(max_retries):
        try:
            return call_groq(transcript)
        except RateLimitError:
            wait = 5 * (attempt + 1)
            print(f"  [rate limited] waiting {wait}s (retry {attempt+1}/{max_retries})...")
            time.sleep(wait)
        except BadRequestError as e:
            print(f"  [error] Groq rejected the generation: {e}")
            return None
    return None


def score_transcript(transcript: str) -> FeedbackScore | None:
    raw_output = call_groq_with_retry(transcript)
    if raw_output is None:
        return None
    try:
        data = json.loads(raw_output)
        return FeedbackScore.model_validate(data)
    except (json.JSONDecodeError, ValidationError) as e:
        print(f"  [error] could not parse/validate feedback response: {e}")
        return None


def main():
    transcripts = get_transcripts()
    for name, transcript in transcripts.items():
        print("=" * 70)
        print(f"Transcript: {name}")
        score = score_transcript(transcript)

        if score is None:
            print("  SCORING FAILED")
            continue

        print(f"  STAR:    {score.star.score}/5  -- {score.star.tip}")
        print(f"  Depth:   {score.depth.score}/5  -- {score.depth.tip}")
        print(f"  Clarity: {score.clarity.score}/5  -- {score.clarity.tip}")
        print()


if __name__ == "__main__":
    main()
